### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jayaramsurya** [AgoraIO-Community/Agora-RTC-SDK-for-React-Native#29]
2019-09-05 10:49:55.163 26484-26518/com.rnapi D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
2019-09-05 10:49:55.447 26484-26517/com.rnapi I/ReactNativeJS: Running application "RNapi" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
2019-09-05 10:49:55.513 26484-26484/com.rnapi E/art: No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
2019-09-05 10:49:55.514 26484-26484/com.rnapi D/AndroidRuntime: Shutting down VM
2019-09-05 10:49:55.515 26484-26484/com.rnapi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rnapi, PID: 26484
    java.lang.UnsatisfiedLinkError: No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
        at io.agora.rtc.internal.RtcEngineImpl.nativeLog(Native Method)
        at io.agora.rtc.internal.Logging.log(Logging.java:25)
        at io.agora.rtc.internal.Logging.i(Logging.java:49)
        at io.agora.rtc.internal.RtcEngineImpl.checkIfInUIThread(RtcEngineImpl.java:149)
        at io.agora.rtc.RtcEngine.CreateRendererView(RtcEngine.java:875)
        at com.rnapi.SurfaceViewManager.createViewInstance(SurfaceViewManager.java:37)
        at com.rnapi.SurfaceViewManager.createViewInstance(SurfaceViewManager.java:18)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1013)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:984)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:685)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2019-09-05 10:49:55.529 26484-26484/com.rnapi I/Process: Sending signal. PID: 26484 SIG: 9

**Comment by jayaramsurya** [comment]
AnyOne help me i am struck here.

**Comment by Matrixbirds** [comment]
We have already deprecated this sdk instead [react-native-agora](https://github.com/syanbo/react-native-agora). You could try our [quickstart](https://github.com/agoraio-community/agora-rn-quickstart)

**Comment by jayaramsurya** [comment]
Thanks, Dude..!
